service: graphql

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: any
        cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules:
    packagePath: './package.json'